### ISSUE TITLE
🐛 [BUG] - Neither "Agents" nor "Hotkeys" work

### ISSUE THREAD

**Issue by kuzzmi** [ClassicUO/classicuo-web#99]
### Description

Clicking on either "Agents" or "Hotkeys" results in an error bar. Sidebar becomes unusable.

Shard is "UOAlive" if that matters.

<img width="883" alt="Screenshot 2024-07-07 at 00 43 20" src="https://github.com/ClassicUO/classicuo-web/assets/1727140/3c47c78e-b231-43f3-95a1-733148d35890">

### Reproduction steps

```bash
1. Enter the world
2. Click on "Agents"
3. See error

1. Enter the world
2. Click on "Hotkeys"
3. See error
```

### Logs or Error messages

```bash
// Agents
TypeError: Cannot read properties of undefined (reading 'logOpen')
    at LootAgent (https://play.classicuo.org/index-FaVcpIcY.js:646:1389)
    at Xh (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:139440)
    at Wk (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:202045)
    at Vk (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:190026)
    at Uk (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:189947)
    at Jk (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:189797)
    at Ok (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:186268)
    at Fk (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:186712)
    at jg (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:121310)
    at https://play.classicuo.org/vendor-Wys8IVWQ.js:1:183962

// Hotkeys
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at HotKeys (https://play.classicuo.org/index-FaVcpIcY.js:1058:912)
    at Xh (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:139440)
    at Wk (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:202045)
    at Vk (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:190026)
    at Uk (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:189947)
    at Jk (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:189797)
    at Ok (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:186268)
    at Fk (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:186712)
    at jg (https://play.classicuo.org/vendor-Wys8IVWQ.js:1:121310)
    at https://play.classicuo.org/vendor-Wys8IVWQ.js:1:183962
```

### Browsers

Chrome

### OS

Mac

**Comment by kuzzmi** [comment]
I have tried so many things prior to filing the bug, but after posting it and creating a new profile, things started working well...
